export interface City {
  id: string;
  name: string;
  lat: number;
  lng: number;
  country: string;
  flag: string;
  continent: Continent;
}

export type Continent =
  | "north_america"
  | "south_america"
  | "europe"
  | "africa"
  | "asia"
  | "oceania"
  | "middle_east";

export const CITIES: Record<string, City> = {
  new_york: {
    id: "new_york",
    name: "New York",
    lat: 40.7128,
    lng: -74.006,
    country: "United States",
    flag: "🇺🇸",
    continent: "north_america",
  },
  los_angeles: {
    id: "los_angeles",
    name: "Los Angeles",
    lat: 34.0522,
    lng: -118.2437,
    country: "United States",
    flag: "🇺🇸",
    continent: "north_america",
  },
  chicago: {
    id: "chicago",
    name: "Chicago",
    lat: 41.8781,
    lng: -87.6298,
    country: "United States",
    flag: "🇺🇸",
    continent: "north_america",
  },
  toronto: {
    id: "toronto",
    name: "Toronto",
    lat: 43.6532,
    lng: -79.3832,
    country: "Canada",
    flag: "🇨🇦",
    continent: "north_america",
  },
  mexico_city: {
    id: "mexico_city",
    name: "Mexico City",
    lat: 19.4326,
    lng: -99.1332,
    country: "Mexico",
    flag: "🇲🇽",
    continent: "north_america",
  },
  sao_paulo: {
    id: "sao_paulo",
    name: "São Paulo",
    lat: -23.5505,
    lng: -46.6333,
    country: "Brazil",
    flag: "🇧🇷",
    continent: "south_america",
  },
  buenos_aires: {
    id: "buenos_aires",
    name: "Buenos Aires",
    lat: -34.6037,
    lng: -58.3816,
    country: "Argentina",
    flag: "🇦🇷",
    continent: "south_america",
  },
  london: {
    id: "london",
    name: "London",
    lat: 51.5074,
    lng: -0.1278,
    country: "United Kingdom",
    flag: "🇬🇧",
    continent: "europe",
  },
  paris: {
    id: "paris",
    name: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    country: "France",
    flag: "🇫🇷",
    continent: "europe",
  },
  madrid: {
    id: "madrid",
    name: "Madrid",
    lat: 40.4168,
    lng: -3.7038,
    country: "Spain",
    flag: "🇪🇸",
    continent: "europe",
  },
  berlin: {
    id: "berlin",
    name: "Berlin",
    lat: 52.52,
    lng: 13.405,
    country: "Germany",
    flag: "🇩🇪",
    continent: "europe",
  },
  rome: {
    id: "rome",
    name: "Rome",
    lat: 41.9028,
    lng: 12.4964,
    country: "Italy",
    flag: "🇮🇹",
    continent: "europe",
  },
  istanbul: {
    id: "istanbul",
    name: "Istanbul",
    lat: 41.0082,
    lng: 28.9784,
    country: "Turkey",
    flag: "🇹🇷",
    continent: "europe",
  },
  moscow: {
    id: "moscow",
    name: "Moscow",
    lat: 55.7558,
    lng: 37.6173,
    country: "Russia",
    flag: "🇷🇺",
    continent: "europe",
  },
  lagos: {
    id: "lagos",
    name: "Lagos",
    lat: 6.5244,
    lng: 3.3792,
    country: "Nigeria",
    flag: "🇳🇬",
    continent: "africa",
  },
  cairo: {
    id: "cairo",
    name: "Cairo",
    lat: 30.0444,
    lng: 31.2357,
    country: "Egypt",
    flag: "🇪🇬",
    continent: "africa",
  },
  nairobi: {
    id: "nairobi",
    name: "Nairobi",
    lat: -1.2921,
    lng: 36.8219,
    country: "Kenya",
    flag: "🇰🇪",
    continent: "africa",
  },
  johannesburg: {
    id: "johannesburg",
    name: "Johannesburg",
    lat: -26.2041,
    lng: 28.0473,
    country: "South Africa",
    flag: "🇿🇦",
    continent: "africa",
  },
  dubai: {
    id: "dubai",
    name: "Dubai",
    lat: 25.2048,
    lng: 55.2708,
    country: "UAE",
    flag: "🇦🇪",
    continent: "middle_east",
  },
  riyadh: {
    id: "riyadh",
    name: "Riyadh",
    lat: 24.7136,
    lng: 46.6753,
    country: "Saudi Arabia",
    flag: "🇸🇦",
    continent: "middle_east",
  },
  mumbai: {
    id: "mumbai",
    name: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    country: "India",
    flag: "🇮🇳",
    continent: "asia",
  },
  delhi: {
    id: "delhi",
    name: "Delhi",
    lat: 28.7041,
    lng: 77.1025,
    country: "India",
    flag: "🇮🇳",
    continent: "asia",
  },
  shanghai: {
    id: "shanghai",
    name: "Shanghai",
    lat: 31.2304,
    lng: 121.4737,
    country: "China",
    flag: "🇨🇳",
    continent: "asia",
  },
  beijing: {
    id: "beijing",
    name: "Beijing",
    lat: 39.9042,
    lng: 116.4074,
    country: "China",
    flag: "🇨🇳",
    continent: "asia",
  },
  tokyo: {
    id: "tokyo",
    name: "Tokyo",
    lat: 35.6762,
    lng: 139.6503,
    country: "Japan",
    flag: "🇯🇵",
    continent: "asia",
  },
  seoul: {
    id: "seoul",
    name: "Seoul",
    lat: 37.5665,
    lng: 126.978,
    country: "South Korea",
    flag: "🇰🇷",
    continent: "asia",
  },
  singapore: {
    id: "singapore",
    name: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    country: "Singapore",
    flag: "🇸🇬",
    continent: "asia",
  },
  bangkok: {
    id: "bangkok",
    name: "Bangkok",
    lat: 13.7563,
    lng: 100.5018,
    country: "Thailand",
    flag: "🇹🇭",
    continent: "asia",
  },
  kuala_lumpur: {
    id: "kuala_lumpur",
    name: "Kuala Lumpur",
    lat: 3.139,
    lng: 101.6869,
    country: "Malaysia",
    flag: "🇲🇾",
    continent: "asia",
  },
  sydney: {
    id: "sydney",
    name: "Sydney",
    lat: -33.8688,
    lng: 151.2093,
    country: "Australia",
    flag: "🇦🇺",
    continent: "oceania",
  },
};

export type CityKey = keyof typeof CITIES;
export const CITY_LIST = Object.values(CITIES);
